# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_code', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('translator', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField()),
                ('revision_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
